name: Build & CI

on:
  push:
    paths:
      - 'todo/**'

  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: todo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew test

      - name: Build todo
        run: ./gradlew assemble
