name: Build & CI

on:
  push:
    paths:
      - 'todo/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build todo
        run: cd todo && ./gradlew build
